use_frameworks!

target 'HLIntegrationlibrary_Example' do
#  pod 'HLIntegrationlibrary', :path => '../'
#pod 'WHKit', '~>1.3.3'
  target 'HLIntegrationlibrary_Tests' do
    inherit! :search_paths

    
  end
end
